server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mariadb://auth-db:3306/auth_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
