services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - product-service
      - cart-service
    networks:
      - backend

  auth-service:
    build: ./auth-service
    environment:
      - DB_HOST=auth-db
    depends_on:
      - auth-db
    networks:
      - backend

  product-service:
    build: ./product-service
    depends_on:
      - product-db
    networks:
      - backend

  cart-service:
    build: ./cart-service
    environment:
      - DB_HOST=cart-db
    depends_on:
      - cart-db
    networks:
      - backend

  auth-db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
    networks:
      - backend

  product-db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_db
    networks:
      - backend

  cart-db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cart_db
    networks:
      - backend


networks:
  backend:
    driver: bridge
