server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**
        - id: product-service
          uri: http://product-service:8082
          predicates:
            - Path=/api/products/**
        - id: cart-service
          uri: http://cart-service:8083
          predicates:
            - Path=/api/cart/**
