server:
  port: 8083

spring:
  application:
    name: cart-service

  security:
    oauth2:
      resourceserver:
        jwt:
          secret: secretKeyY5FtNP6wGx7BKnmpse4Drd2XUSgLajQHy

  datasource:
    url: jdbc:mariadb://cart-db:3306/cart_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect


product:
  service:
    url: http://gateway:8080/api/products